# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
ProductCategory.destroy_all
User.destroy_all
Product.destroy_all
Category.destroy_all

jack = User.create(first_name: "Jack", last_name: "Jackson", username: "jack_ant", bio: "love insects", password: "oiwnlkno2i")
jim = User.create(first_name: "Jim", last_name: "Parson", username: "jim_tuna", bio: "love tea, coffee, food", password: "iewokdn")
liz = User.create(first_name: "Liz", last_name: "Zo",username: "liz_pie", bio: "love singing, hates insects", password: "i24ijlkxoi")
jasper = User.create(first_name: "Jasper", last_name: "Reed",username: "deerreed", bio: "food is the best thing about life, i don't care what anyone says", password: "fish")
jen = User.create(first_name: "Jen", last_name: "Pick", username: "jen_jam", bio: "mountains, swimming, and fishing", password: "floop")
dwight = User.create(first_name: "Dwight", last_name: "Shrute", username: "eco_man", bio: "bears, beats, battlestar galactica", password: "mose")
pam = User.create(first_name: "Pam", last_name: "Beesly", username: "art_for_you", bio: "love art but don't have time for it", password: "jimmy4")
michael = User.create(first_name: "Michael", last_name: "Scott", username: "best_boss", bio: "NO! NO! NO! NO!", password: "dunder0101")
andy = User.create(first_name: "Andy", last_name: "Bernard", username: "cornel_big_red", bio: "wish we knew when we were in the good ol days", password: "bigred44")
ryan = User.create(first_name: "Ryan", last_name: "Howard", username: "wunderkind", bio: "I have no clue who michael is", password: "bowlingrox")

corgi_pillow = Product.create(name: "Mr.Corgi", price: 15.99, description: "Corgi Shaped Pillow", owner_id: User.first.id)
water_bottle = Product.create(name: "Simply", price: 20.00, description: "The best water bottle ever", owner_id: User.second.id)
used_laptop = Product.create(name: "Computer", price: 249.99, description: "Windows 10, 5 years old", owner_id: User.first.id)
snoopy_mug = Product.create(name: "Snoop Dogg", price: 15.99, description: "Vintage, 50 years old", owner_id: User.third.id)
samsung_tv = Product.create(name: "Samsung xB432", price: 399.99, description: "50 inch flat-screen, best tv on the market, last tv you'll ever need to buy", owner_id: rand(1...10))
sony_tv = Product.create(name: "Sony joi987832", price: 599.99, description: "50 inch flat-screen, best tv on the market, last tv you'll ever need to buy", owner_id: rand(1...10))
red_bull = Product.create(name: "RedBull", price: 9.99, description: "gives you wings", owner_id: rand(1...10))
monitor_speaker = Product.create(name: "Presonus", price: 99.99, description: "near field studio monitor (pair)", owner_id: rand(1...10))
mini_fridge = Product.create(name: "HomeLabs Mini-Fridge", price: 189.99, description: "3.3 cubic feet under counter refrigerator with small freezer", owner_id: rand(1...10))
hat = Product.create(name: "Carhartt Hat", price: 19.99, description: "One Size", owner_id: rand(1...10))
headphones = Product.create(name: "Beats", price: 299.99, description: "best sound quality in a small form that everyone will love", owner_id: rand(1...10))
power_drill = Product.create(name: "Power Drill", price: 59.99, description: "only drill you'll ever need", owner_id: rand(1...10))
power_saw = Product.create(name: "Power Saw", price: 89.99, description: "only saw you'll ever need", owner_id: rand(1...10))
monopoly_game = Product.create(name: "Monopoly", price: 10.99, description: "trimph over your friends, rule the board", owner_id: rand(1...10))
field_notes = Product.create(name: "Field Notes", price: 9.99, description: "best notebook ever", owner_id: rand(1...10))
pet_food = Product.create(name: "Fantsy Feast", price: 17.99, description: "your pets will love you... if they don't already", owner_id: rand(1...10))
rocking_chair = Product.create(name: "Rocking Chair", price: 2000.00, description: "most rocking chair ever", owner_id: rand(1...10))
shovel = Product.create(name: "Shovel", price: 29.99, description: "if you need to dig a hole, this is the shovel for you", owner_id: rand(1...10))
car = Product.create(name: "Austin Martin DB09", price: 6000000.00, description: "drive like 007 and find the limit of every road as you cruse into a sunset", owner_id: rand(1...10))
soccer_ball = Product.create(name: "Soccer Ball", price: 5.99, description: "soccer ball... what more could you want or need", owner_id: rand(1...10))
football = Product.create(name: "Football", price: 3.99, description: "football... what more could you want", owner_id: rand(1...10))
tennis_ball = Product.create(name: "Tennis Ball", price: 10.99, description: "highest grade yellow sphere", owner_id: rand(1...10))
key_chain = Product.create(name: "Wooden Keychain", price: 32.75, description: "if you like wooden keychains, i have got something for you", owner_id: rand(1...10))

toy = Category.create(name: "toy")
electronic = Category.create(name: "electronic")
home_goods = Category.create(name: "home goods")
accessories = Category.create(name: "accessories")
kids = Category.create(name: "kids")
food = Category.create(name: "food")
handmade = Category.create(name: "handmade")
books = Category.create(name: "books")
garden = Category.create(name: "garden")
clothing = Category.create(name: "clothing")
movies = Category.create(name: "movies")
tools = Category.create(name: "tools")
automotive = Category.create(name: "automotive")
sports = Category.create(name: "sports")
health = Category.create(name: "health")
shoes = Category.create(name: "shoes")
games = Category.create(name: "games")
pet_supplies = Category.create(name: "pet supplies")

pc1 = ProductCategory.create(category_id: Category.first.id, product_id: Product.first.id)
pc2 = ProductCategory.create(category_id: Category.second.id, product_id: Product.third.id)
pc3 = ProductCategory.create(category_id: Category.third.id, product_id: Product.fourth.id)
pc4 = ProductCategory.create(category_id: Category.fourth.id, product_id: Product.second.id)
pc5 = ProductCategory.create(category_id: toy.id, product_id: monopoly_game.id)
pc6 = ProductCategory.create(category_id: toy.id, product_id: tennis_ball.id)
pc7 = ProductCategory.create(category_id: toy.id, product_id: football.id)
pc8 = ProductCategory.create(category_id: toy.id, product_id: soccer_ball.id)
pc9 = ProductCategory.create(category_id: electronic.id, product_id: samsung_tv.id)
pc10 = ProductCategory.create(category_id: electronic.id, product_id: sony_tv.id)

pc11 = ProductCategory.create(category_id: electronic.id, product_id: mini_fridge.id)
pc12 = ProductCategory.create(category_id: electronic.id, product_id: monitor_speaker.id)
pc13 = ProductCategory.create(category_id: electronic.id, product_id: headphones.id)
pc14 = ProductCategory.create(category_id: electronic.id, product_id: power_drill.id)
pc15 = ProductCategory.create(category_id: electronic.id, product_id: power_saw.id)
pc16 = ProductCategory.create(category_id: home_goods.id, product_id: mini_fridge.id)
pc17 = ProductCategory.create(category_id: home_goods.id, product_id: monopoly_game.id)
pc18 = ProductCategory.create(category_id: home_goods.id, product_id: rocking_chair.id)
pc19 = ProductCategory.create(category_id: home_goods.id, product_id: power_drill.id)
pc20 = ProductCategory.create(category_id: home_goods.id, product_id: power_saw.id)

pc21 = ProductCategory.create(category_id: accessories.id, product_id: key_chain.id)
pc22 = ProductCategory.create(category_id: kids.id, product_id: tennis_ball.id)
pc23 = ProductCategory.create(category_id: kids.id, product_id: football.id)
pc24 = ProductCategory.create(category_id: kids.id, product_id: soccer_ball.id)
pc25 = ProductCategory.create(category_id: kids.id, product_id: corgi_pillow.id)
pc26 = ProductCategory.create(category_id: food.id, product_id: red_bull.id)
pc27 = ProductCategory.create(category_id: handmade.id, product_id: rocking_chair.id)
pc28 = ProductCategory.create(category_id: handmade.id, product_id: key_chain.id)
pc29 = ProductCategory.create(category_id: books.id, product_id: field_notes.id)
pc30 = ProductCategory.create(category_id: garden.id, product_id: shovel.id)

pc31 = ProductCategory.create(category_id: garden.id, product_id: water_bottle.id)
pc32 = ProductCategory.create(category_id: clothing.id, product_id: hat.id)
pc33 = ProductCategory.create(category_id: tools.id, product_id: power_saw.id)
pc34 = ProductCategory.create(category_id: tools.id, product_id: power_drill.id)
pc35 = ProductCategory.create(category_id: tools.id, product_id: shovel.id)
pc36 = ProductCategory.create(category_id: automotive.id, product_id: car.id)
pc37 = ProductCategory.create(category_id: sports.id, product_id: tennis_ball.id)
pc38 = ProductCategory.create(category_id: sports.id, product_id: soccer_ball.id)
pc39 = ProductCategory.create(category_id: sports.id, product_id: football.id)
pc40 = ProductCategory.create(category_id: health.id, product_id: water_bottle.id)

pc41 = ProductCategory.create(category_id: games.id, product_id: monopoly_game.id)
pc42 = ProductCategory.create(category_id: games.id, product_id: soccer_ball.id)
pc43 = ProductCategory.create(category_id: games.id, product_id: tennis_ball.id)
pc44 = ProductCategory.create(category_id: games.id, product_id: football.id)
pc45 = ProductCategory.create(category_id: pet_supplies.id, product_id: pet_food.id)

review1 = Review.create(rating: 4.0, content: "Oh my gawd I love this", product_id: Product.first.id, user_id: User.first.id)
review2 = Review.create(rating: 3.6, content: "Love the design but not so much about the functionality", product_id: Product.first.id, user_id: User.second.id)
review3 = Review.create(rating: 5.0, content: "AHMAZING", product_id: Product.second.id, user_id: User.first.id)
review4 = Review.create(rating: 2.0, content: "Meh", product_id: Product.third.id, user_id: User.first.id)
review5 = Review.create(rating: 3.1, content: "It's alright", product_id: Product.fourth.id, user_id: User.third.id)

